_target_: src.utils.make_grid
options:
  - scaling:
      - _target_: sklearn.preprocessing.MinMaxScaler
    clf:
      - _target_: xgboost.XGBClassifier
        objective: binary:logistic
        nthread: 1
        eval_metric: auc
    clf__learning_rate:
      _target_: scipy.stats.uniform
      loc: 0.1
      scale: 0.8
    clf__n_estimators:
      _target_: scipy.stats.randint
      low: 120
      high: 220
    clf__max_depth:
      _target_: scipy.stats.randint
      low: 6
      high: 10
