_target_: src.utils.make_grid
options:
  - scaling:
      - passthrough
  - clf:
      - _target_: sklearn.svm.SVC
        probability: true
    clf__C:
      _target_: scipy.stats.loguniform
      a: 0.01
      b: 1.0
    clf__gamma:
      _target_: scipy.stats.loguniform
      a: 0.01
      b: 1.0
